import { Hero } from './hero';

export const HEROES: Hero[] = [
    { 
        id: 11, 
        name: 'Mercy', 
        img: 'mercy.png', 
        bg: 'bg-mercy.jpg', 
        occupation: 'Field Medic, First Responder', 
        role: 'Support', 
        difficulty: 1, 
        abilities:[],
        description:'Mercy’s Valkyrie Suit helps keep her close to teammates like a guardian angel; healing, resurrecting or strengthening them with the beams emanating from her Caduceus Staff.' 
    },
    {
        id: 12,
        name: 'Brigitte',
        img: 'brigitte.png',
        bg: 'bg-brigitte.jpg',
        occupation:'Mechanical Engineer, Adventurer',
        role: 'Support',
        difficulty: 1,
        abilities: [],
        description:'Brigitte specializes in armor. She can throw Repair Packs to heal teammates, or automatically heal nearby allies when she damages foes with her Flail. Her Flail is capable of a wide swing to strike multiple targets, or a Whip Shot that stuns an enemy at range. When entering the fray, Barrier Shield provides personal defense while she attacks enemies with Shield Bash. Brigitte’s ultimate ability, Rally, gives her a substantial short-term boost of speed and provides long-lasting armor to all her nearby allies.',
    },
    {
        id: 13,
        name: 'Winston',
        img: 'winston.png',
        bg: 'bg-winston.jpg',
        occupation:'Scientist, Adventurer',
        role: 'Tank',
        difficulty: 2,
        abilities: [],
        description:'Winston wields impressive inventions—a jump pack, electricity-blasting Tesla Cannon, portable shield projector and more—with literal gorilla strength.',
    },
    {
        id: 14,
        name: 'Sombra',
        img: 'sombra.png',
        bg: 'bg-sombra.jpg',
        occupation:'Hacker',
        role: 'Offense',
        difficulty: 3,
        abilities: [],
        description:'Stealth and debilitating attacks make Sombra a powerful infiltrator. Her hacking can disrupt her enemies, ensuring they\'re easier to take out, while her EMP provides the upper hand against multiple foes at once. Sombra’s ability to Translocate and camouflage herself makes her a hard target to pin down.',
    },
    {
        id: 15,
        name: 'Widowmaker',
        img: 'widowmaker.png',
        bg: 'bg-widowmaker.jpg',
        occupation:'Assassin',
        role: 'Defense',
        difficulty:2,
        abilities: [],
        description:'Widowmaker equips herself with whatever it takes to eliminate her targets, including mines that dispense poisonous gas, a visor that grants her squad infra-sight, and a powerful sniper rifle that can fire in fully-automatic mode.',
    },
    {
        id: 16,
        name: 'Doomfist',
        img: 'doomfist.png',
        bg: 'bg-doomfist.jpg',
        occupation:'Mercenary',
        role: 'Offense',
        difficulty: 3,
        abilities: [],
        description:'Doomfist\'s cybernetics make him a highly-mobile, powerful frontline fighter. In addition to dealing ranged damage with his Hand Cannon, Doomfist can slam the ground, knock enemies into the air and off balance, or charge into the fray with his Rocket Punch. When facing a tightly packed group, Doomfist leaps out of view, then crashes down to earth with a spectacular Meteor Strike.',
    },
    {
        id: 17,
        name: 'Hanzo',
        img: 'hanzo.png',
        bg: 'bg-hanzo.jpg',
        occupation:'Mercenary, Assassin',
        role: 'Defense',
        difficulty:3,
        abilities: [],
        description:'Hanzo\'s versatile arrows can reveal his enemies or fragment to strike multiple targets. He can scale walls to fire his bow from on high, or summon a titanic spirit dragon.',
    },
    {
        id: 18,
        name: 'Mei',
        img: 'mei.png',
        bg: 'bg-mei.jpg',
        occupation:'Climatologist, Adventurer',
        role: 'Defense',
        difficulty: 3,
        abilities: [],
        description:'Mei\'s weather-altering devices slow opponents and protect locations. Her Endothermic Blaster unleashes damaging icicles and frost streams, and she can Cryo-Freeze herself to guard against counterattacks, or obstruct the opposing team\'s movements with an Ice Wall.',
    },
    {
        id: 19,
        name: 'Tracer',
        img: 'tracer.png',
        bg: 'bg-tracer.jpg',
        occupation:'Adventurer',
        role: 'Offense',
        difficulty: 2,
        abilities: [],
        description:'Toting twin pulse pistols, energy-based time bombs, and rapid-fire banter, Tracer is able to "blink" through space and rewind her personal timeline as she battles to right wrongs the world over.',
    },
    {
        id: 20,
        name: 'D.Va',
        img: 'dva.png',
        bg: 'bg-dva.jpg',
        occupation:'Pro Gamer (formerly), Mech Pilot',
        role: 'Tank',
        difficulty: 2,
        abilities: [],
        description:'D.Va\'s mech is nimble and powerful—its twin Fusion Cannons blast away with autofire at short range, and she can use its Boosters to barrel over enemies and obstacles, or deflect attacks with her projectile-dismantling Defense Matrix.',
    },
    {
        id: 21,
        name: 'Genji',
        img: 'genji.png',
        bg: 'bg-genji.jpg',
        occupation:'Adventurer',
        role: 'Offense',
        difficulty: 3,
        abilities: [],
        description:'Genji flings precise and deadly Shuriken at his targets, and uses his technologically-advanced katana to deflect projectiles or deliver a Swift Strike that cuts down enemies.',
    },
    {
        id: 22,
        name: 'Roadhog',
        img: 'roadhog.png',
        bg: 'bg-roadhog.jpg',
        occupation:'Enforcer (formerly), Bodyguard',
        role: 'Tank',
        difficulty: 1,
        abilities: [],
        description:'Roadhog uses his signature Chain Hook to pull his enemies close before shredding them with blasts from his Scrap Gun. He’s hardy enough to withstand tremendous damage, and can recover his health with a short breather.',
    },
    {
        id: 23,
        name: 'Ana',
        img: 'ana.png',
        bg: 'bg-ana.jpg',
        occupation:'Bounty Hunter',
        role: 'Support',
        difficulty: 3,
        abilities: [],
        description:'Ana\'s versatile arsenal allows her to affect heroes all over the battlefield. Her Biotic Rifle rounds and Biotic Grenades heal allies and damage or impair enemies; her sidearm tranquilizes key targets, and Nano Boost gives one of her comrades a considerable increase in power.',
    },
    {
        id: 24,
        name: 'Pharah',
        img: 'pharah.png',
        bg: 'bg-pharah.jpg',
        occupation:'Security Chief',
        role: 'Offense',
        difficulty: 1,
        abilities: [],
        description:'Soaring through the air in her combat armor, and armed with a launcher that lays down high-explosive rockets, Pharah is a force to be reckoned with.',
    },
    {
        id: 25,
        name: 'Junkrat',
        img: 'junkrat.png',
        bg: 'bg-junkrat.jpg',
        occupation:'Anarchist, Thief, Demolitionist, Mercenary, Scavenger',
        role: 'Damage',
        difficulty: 2,
        abilities: [],
        description:'Junkrat\'s area-denying armaments include a Frag Launcher that lobs bouncing grenades, Concussion Mines that send enemies flying, and Steel Traps that stop foes dead in their tracks.',
    },
    {
        id: 26,
        name: 'Reaper',
        img: 'reaper.png',
        bg: 'bg-reaper.jpg',
        occupation:'Mercenary',
        role: 'Damage',
        difficulty: 1,
        abilities: [],
        description:'Hellfire Shotguns, the ghostly ability to become immune to damage, and the power to step between shadows make Reaper one of the deadliest beings on Earth.',
    },
    {
        id: 27,
        name: 'Lucio',
        img: 'lucio.png',
        bg: 'bg-lucio.jpg',
        occupation:'DJ, Freedom Fighter',
        role: 'Support',
        difficulty: 2,
        abilities: [],
        description:'On the battlefield, Lúcio’s cutting-edge Sonic Amplifier buffets enemies with projectiles and knocks foes back with blasts of sound. His songs can both heal his team or boost their movement speed, and he can switch between tracks on the fly.',
    },
    {
        id: 28,
        name: 'McCree',
        img: 'mccree.png',
        bg: 'bg-mccree.jpg',
        occupation:'Bounty Hunter',
        role: 'Damage',
        difficulty: 2,
        abilities: [],
        description:'Armed with his Peacekeeper revolver, McCree takes out targets with deadeye precision and dives out of danger with eagle-like speed.',
    }


];